apiVersion: v1
kind: Service
metadata:
  name: invoicetool-service
  labels:
    app: invoicetool
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: invoicetool